[package]
name = "newsie-api"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "3"
clap = "2.33.3"
serde = "1.0.130"
serde_json = "1.0"
diesel = { version = "1.4.4", features = ["sqlite"] }
dotenv = "0.15.0"